### ISSUE TITLE
Error: Cannot find module './config'

### ISSUE THREAD

**Issue by marcelschool** [Snapchat/express-4.x-passport-snapchat-example#2]
`Error: Cannot find module './config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/hosts/express-4.x-passport-snapchat-example/server.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)`

**Comment by marcelschool** [comment]
Solution (not in documentation) make a config.js file in the root map with you tokens:

```
const config = {
    CLIENT_ID: "",
    CLIENT_SECRET: ""
};

module.exports = config;
```
